### ISSUE TITLE
Schema updates

### ISSUE THREAD

**Issue by jkiddo** [DIGGSweden/dgc-java#17]
Should this project be updated with the schemas from https://github.com/ehn-digital-green-development/ehn-dgc-schema instead of using the one from https://github.com/ehn-digital-green-development/hcert-schema/blob/main/eu_dgc_v1_schema.json ?

**Comment by martin-lindstrom** [comment]
As soon as we know which of the two versions to use we'll update the library with the final schema.

As it is now the schema in https://github.com/ehn-digital-green-development/ehn-dgc-schema has a lot of issues that need to be resolved.
