### ISSUE TITLE
Test testSimpleCreate in DefaultBarcodeCreatorTest fails on any computer running a system characterset other than "Latin I"

### ISSUE THREAD

**Issue by jozemlakar** [DIGGSweden/dgc-java#52]
Test testSimpleCreate in DefaultBarcodeCreatorTest fails on any computer running a system characterset other than "Latin I". This is due to combination of character Ö being available in simple charset of "Latin I" but not being available in other simple charsets.

I tried using UTF-8 encoding both in literal values as well as in building the QR code, but was unsuccessful.

**Comment by martin-lindstrom** [comment]
But the Java files should all be in UTF-8. Could you elaborate?

**Comment by jozemlakar** [comment]
Maybe. Probablly. The fact is that the test fails. And the fact is that the test generates QR code with the string while using encoding "null", meaning default.
I aslo tried to change the value to proper UTF-8 and set the encoding for the string to byte conversion but no love.

Regardless, we forked the repo, changed the value so we don't have a problem. Just thought others might benefit from this fix.

**Comment by martin-lindstrom** [comment]
I have written a stupid testcase anyway. In all practical cases a Base45 encoded string will be used, and that string is pure ASCII. But I'll look into it anyway.
