### ISSUE TITLE
Incorrect Instant serialization to JSON

### ISSUE THREAD

**Issue by jozemlakar** [DIGGSweden/dgc-java#66]
We are using dgc-java in Slovenia, forked at https://github.com/ixtlan-team/dgc-java
We have prepared the DGCs and found that for "test" DGCs that include sc field, we get a value of:
`"sc": "2021-06-04T10:46:25.619935900Z"`
This value is not well recieved by the verification app, as fraction has too many digits (9).
We have also found that in samples submitted by SE, value is 
'"sc": "2021-06-02T06:02:13.262564Z"'
This value is correct, it has 6 digits in fraction.

You can disregard this issue and mark it closed and we will try and resolve the issue on our own. But if you feel that you want this resolved for you as well, then let us know, what the preffered way would be.

From what we found the correct way would be to fix the 'ObjectMapper jsonMapper' in 'DigitalCovidCertificate'.
Alternative would be to add JsonFormatter to the Instant field in 'TestStatement'

**Comment by martin-lindstrom** [comment]
@jozemlakar Thanks for pointing it out. The PR https://github.com/DIGGSweden/dgc-java/pull/67 fixes this.

**Comment by jozemlakar** [comment]
PR #67 removes all fractions. As test show, it should hold EXACTLY 6 digits for fractions.

**Comment by martin-lindstrom** [comment]
6 fractions? From where did you get that information?

From the [specification](https://teams.microsoft.com/l/file/d6c6f943-6ad3-433b-b12b-2cc61fca4ee0?tenantId=b24c8b06-522c-46fe-9080-70926f8dddb1&fileType=docx&objectUrl=https%3A%2F%2Feceuropaeu.sharepoint.com%2Fteams%2FGRP-eHNTechIOPSG%2FShared%2520Documents%2FGeneral%2FOngoing%2520work%2FJSON%2520Schema%2FJSON%2520Schema%2520Specification-v1.2.1.docx&baseUrl=https%3A%2F%2Feceuropaeu.sharepoint.com%2Fteams%2FGRP-eHNTechIOPSG&serviceName=aggregatefiles):

The date and time when the test sample was collected. The time MUST include information on the time zone. The value MUST NOT denote the time when the test result was produced.  

Exactly 1 (one) non-empty field MUST be provided.  

One of the following ISO 8601 formats MUST be used. Other options are not supported.  

```
YYYY-MM-DDThh:mm:ssZ 
YYYY-MM-DDThh:mm:ss[+-]hh 
YYYY-MM-DDThh:mm:ss[+-]hhmm 
YYYY-MM-DDThh:mm:ss[+-]hh:mm 
```
Examples: 

```
"sc": "2021-08-20T10:03:12Z"	(UTC time) 
"sc": "2021-08-20T12:03:12+02"	(CEST time) 
"sc": "2021-08-20T12:03:12+0200"	(CEST time) 
"sc": "2021-08-20T12:03:12+02:00"	(CEST time) 
```

**Comment by jozemlakar** [comment]
Yes, I am aware of the spec. However test on dgc-testdata denied samples with 0 fraction digits. Tests might be wrong.

**Comment by martin-lindstrom** [comment]
It’s not the first time they are wrong. I’ll bring it up with them.
