### ISSUE TITLE
Implementation for CertificateProvider missing / documentation where to get the correct certificates is missing

### ISSUE THREAD

**Issue by corona-maps** [DIGGSweden/dgc-java#78]
The DefaultDGCDecoder (https://diggsweden.github.io/dgc-java/javadoc/dgc-create-validate/se/digg/dgc/service/impl/DefaultDGCDecoder.html) needs a CertificateProvider. This, however, is only given as interface. An actual implementation which returns the needed certificates for the countries and most importantly documentation where to get the certificates is missing.

**Comment by martin-lindstrom** [comment]
How to download/get certificates is country-specific and thus there is no implementation of `CertificateProvider` supplied. This is per design. You'll have to implement a provider that is according to your country's way of downloading certificates.
